#!/bin/bash

function usage()
{
    echo "USAGE: ./$0 [options]"
    echo "This script is used to set up Vundle quickly and easily"
    echo
    echo "  -f  =   force delete of any existing ~/.vim folder"
    exit 0
}

# Configurable variables
dotvim=".vim"
force_delete=0

while getopts "fh?" option; do
    case $option in
        f) force_delete=1 ;;
        *) usage ;;
    esac
done
shift $((OPTIND-1))


# All of the setup happens from the root folder
curdir=$(pwd)
cd ~
rootdir=$(pwd)

# $1 = message, $2 = returnv value
function all_done()
{
    # Restore to the original folder
    cd $curdir
    echo
    echo $1
    exit $2
}

# Check if we would overwrite an existing configuration
if [ -d "$rootdir/$dotvim/bundle" ]; then
    if [ $force_delete -eq 1 ]; then
        echo 
        echo "Removing folder:"
        echo "  ~/$dotvim/bundle"
        rm -rf "$rootdir/$dotvim/bundle"
    fi
fi

# Create the folder as needed
if [ ! -d "$rootdir/$dotvim/bundle" ]; then
    echo
    echo "Creating folder:"
    echo "  ~/$dotvim/bundle"
    mkdir -p "$rootdir/$dotvim/bundle/"    
fi

# Download vundle as needed
if [ ! -d "$rootdir/$dotvim/bundle/Vundle.vim" ]; then
    echo
    echo "Cloning vundle to:"
    echo "  ~/$dotvim/bundle/Vundle.vim"
    git clone https://github.com/VundleVim/Vundle.vim.git $rootdir/$dotvim/bundle/Vundle.vim
else
    echo
    echo "Using previously downloaded Vundle."
fi

# Make a backup in case this doesn't go as expected.
if [ -f "$rootdir/.vimrc" ]; then

    # Make a backup if this is a real file. 
    if [ ! -L "$rootdir/.vimrc" ]; then
        
        if [ -L "$rootdir/.vimrc-bak" ]; then
            rm $rootdir/.vimrc-bak
        fi
        
        if [ -f "$rootdir/.vimrc-bak" ]; then
            if [ $force_delete -eq 0 ]; then
                all_done "ERROR: ~/.vimrc-bak already exists! Exiting..." 1
            fi
        fi
        
        echo
        echo "Moving existing ~/.vimrc to ~/.vimrc-bak"
        mv $rootdir/.vimrc $rootdir/.vimrc-bak

    else
        # just remove it because it's a link
        echo
        echo "Removing link:"
        ls -la $rootdir/.vimrc | awk '{print $9" "$10" "$11}'
        rm $rootdir/.vimrc
    fi
fi


echo
echo "Setting up .vimrc..."
if [ ! -f "$curdir/vimrc" ]; then
    cp "$curdir/vimrc-template" "$curdir/vimrc"
fi
ln -s "$curdir/vimrc" "$rootdir/.vimrc"


echo
echo "Calling vim +PluginInstall..."
vim +PluginInstall +qall

echo
echo "Vundle is set up!"
echo "Modify your settings by editing this file:"
echo "  $curdir/vimrc"
echo


all_done "All done!" 0


